namespace Looping_through_Shaleens_jobs
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string[] ShaleenJob =
            { 
                "Queries Issued Report",
                "Refresh Failure - Precision and Recall Analytics",
                "CQR Team Outpatient Back-up Review 2024 (Quarterly)",
                "Monthly DJ03 eRequest Volume",
                "AE Dashboard Missing Data",
                "Update to CPART Status Backlog and Aging Data",
                "Refresh report for HA-5703",
                "Unbilled HIM file Layouts",
                "EPIC MPF VRM Dashboard Modification",
                "Daily automated report missing since 2/6/2024",
                "Create CAC extract for Unbilled Reason Codes for Expanse, Cerner facilities",
                "Refresh report for HA-5745",
                "Refresh report for HA-5744",
                "Refresh report for HA-5746",
                "Profee Worksheet Services report is no longer populating",
                "NCFL Production Scanned Images Missing in CAC",
                "Remove Unit 1554 (west hills) from CAC AS Interim DRG report",
                "Far West SLR Success Matrix 3- Improved MS-DRG Accuracy",
                "Request to refresh the reports for HA-5744",
                "Rehab Power BI Dashboard is not Updating",
                "Rehab Dashboard Listing Ocala as NFD Rehab Facility",
                "Straddle Accounts - Last Coding Activity Date - Daily Report from OPK Pillar",
                " Far West Success Matrix 4: Improved SOI and ROM",
                "Far West SLR Success Matrix 2- Reduction of Queries Launched",
                "Add West Marion Rehab Dashboard Instance",
                "NFD Straddle patient coded between 2/22-3/8",
                "Rehab Dashboard Missing Visits and increase in facility NULL",
                "AE Dashboard Data for SEP 2023",
                "Far West Success Matrix 1- Reduction of CPART volume",
                "Rehab BI Dashboard Pulling a large volume of NULL accounts",
                "AE Dashboard w. Significantly reduced Data",
                "Missing Account Level Detail is HA-5185",
                "Unsubmitted DRG Corrections",
                "WS Services Daily Report for Profee 3M 360 - Coder Failure to Use",
                "CQR Team Outpatient Back-up Review 2024",
                "CQR Team Inpatient DRG Backup Review 2024",
                "AM VRM Analysis Dashboard not refreshing for Monday 2-12-24",
                "AE numbers to be added to AE Dashboard for JAN 2024",
                "Far West SLR Pilot APR DRG Comparison",
                "Vendor name change MiraMed to Coronis - Actionable Edits Report still showing MiraMed",
                "The AE Dashboard is Missing Data from about 01/01/24 onwards",
                "AE Dashboard New Pillar",
                "Lake Nona Inventory showing up again in the Rehab Dashboard",
                "VRM Dashboard Modification-filter including Analysis Priority",
                "Redesign Actionable Edits Dashboard",
                "Submission of UBT notes via SN lines Part 2",
                "New Worklist in NAS CAC Not Populating",
                "Financial Allocation- November 2023 ETL files did not carry over",
                "CPART Extract modification",
                "The AE Dashboard is Missing a Substantial Amount of Missing Data",
                "CAC_CDI_Query reports - DALLAS",
                "AE numbers to be added to AE Dashboard",
                "AE Dashboard is Displaying Cerner Facilities Wrong",
                "CLONE - NICU Fin Allocation Files did not load in to Power BI dashboards",
                "Submission of UBT notes via SN lines",
                "AE Dashboard Not Populating all Pillars and Low volume",
                "Lake Nona Implementation",
                "AE numbers to be added to AE Dashboard",
                "BI Research towards HPF Delinquency Reporting",
                "AE Dashboard Not Populating all Pillars and Low volume",
                "Request for Notes from HIM Unbilled Tool Download",
                "CDRA Financial Allocation Data Issue",
                "AE Dashboard Data Limitation",
                "VRM Analysis Dashboard Not populating",
                "VRM Analysis Dashboard Modification EPIC to Dashboard and Extract Modification",
                "CAC accounts with QRY and other holds; FBCR holds",
                "AE Dashboard Missing MTX Data",
                "VRM Analysis Dashboard report not Updating",
                "The AE Dashboard is Missing Data for Most Pillars",
                "Enhancements Requested to Rehab Report (HT-9595 and HA-1261)",
                "AE numbers to be added to AE Dashboard",
                "Modifications to First Coder/Last Vendor Tables & Reports in AE Dashboard",
                "Reanalysis Queues included in  both Daily and Monthly Analysis CAT File",
                "Analysis Audit Report-Power BI Modification With Pillar/system",
                "VRM Analysis Dashboard Modification",
                "Coding Financial Accuracy",
                "The AE Dashboard is Missing Data",
                "Rehab Power BI Dashboard not capturing all of the Houston Pillar Inventory",
                "Rehab Power BI Dashboard Excluding Nashville Inventory",
                "The AE Dashboard is Missing Data",
                "Missing CAC Documentation Analytics Files",
                "CQR ED Admit Phase 2",
                "Please add edit 1160 to AE Dashboard",
                "The Dashboard is duplicating inventory again.",
                "AE Dashboard Missing Data for nearly 15 Million edits",
                "HIM 3M 360 data file drop for CWTX",
                "AE Dashboard Not Populating all Pillars and VERY Low volume",
                "Rehab Power BI Dashboard Accounts Duplicating on the 10:00 report.",
                "Automated 3M 360 CAC CDI report did not run this morning",
                "Power BI Rehab DC Dashboard Consistently has Issues Refreshing",
                "AE Dashboard Not Populating all Pillars and VERY Low volume",
                "The AE Dashboard is Missing Data",
                "Rehab Power BI Pivot and Detail Report Not Capturing all CAC Queue Volume",
                "Rehab PowerBI Report is missing discharges for 4/24, 4/25 and 4/26",
                "Rehab Power BI Dashboard is not Updating",
                "Add New Edit Numbers to AE Dashboard - Validate 4/24",
                "Second Level Review- Coder Feedback",
                "VRM Analysis Dashboard Not populating",
                "Missing Edit Numbers from AE Dashboard",
                "CQR Team Outpatient CPT Backup Review 2023 (Annual) due 4/5 Validate 4/12",
                "CQR Team Inpatient DRG Backup Review 2023 (Annual) due 4/5 Validate 4/12",
                "Update to CAC_AS Interim_DRG_Report for import to PA",
                "Power BI Rehab DC Dashboard Detail Missing Volumes.",
                "AE Dashboard Not Populating all Pillars and VERY Low volume",
                "Missing Edit Numbers from AE Dashboard 1155 and 1156 - validation on 4/10",
                "CAC_Interim_DRG_Reports",
                "Analysis Productivity Report",
                "Analysis Audit Report is down",
                "New Edits from 3M",
                "OPK Query accounts missing from OMEGA_CAC_VRM_Responded_Query_04-05-2023.CSV",
                "Analysis Dashboard Update",
                "HSC CDI Recon DRG Changes Report",
                "Rehab Power BI Dashboard data is duplicating",
                "The AE Dashboard is Missing Data for Most Pillars",
                "Errors with Data for Parkland and Portsmouth",
                "VRM Analysis Dashboard not populating for 6am pull",
                "CQR Team Outpatient CPT Backup Review 2022 (Quarterly) - Report will run on 3/12",
                "Break-Fix: AE Dashboard: Request to only pull edits displayed in 3M report.",
                "New Edit Numbers for AE Dashboard for FEB 2023 Release - Check 3/13",
                "Rehab Power BI Dashboard is not Updating",
                "CQR Team Inpatient DRG Backup Review 2022 (Quarterly) -",
                "PM VRM Analysis Dashboard did not update",
                "Need a column added to existing extract",
                "Refresh of HA-1418 (Monthly Missing Documentation Snapshot)",
                "AE Dashboard Not Populating all Pillars and VERY Low volume",
                "Computer-assisted CDI Content Prompt Report Due 2/6",
                "Modify - Monthly Accrual File - Facility Coding Due 3/31",
                "NICU Fin Allocation File Correction",
                "The AE Dashboard is only Displaying data for Cerner and Expanse",
                "Daily Scheduled Report for Computer-assisted CDI Content Status Pilot",
                "Enhancement of Rehab Dashboard Refresh Frequency",
                "GeBBS_CACHoldMTURC_01-23-23 report contains old data",
                "EFL History & Physical Report",
                "CAC CDI 00 Query Report",
                "Analysis Dashboard VRM View Tab Modification",
                "New Edit Numbers for AE Dashboard for SP1 2023 Release - due 1/25",
                "Break-Fix: Actionable Edits Power BI Refresh Issue",
                "Break-Fix: Missing Data and Data Fields from AE Dashboard",
                "Expanse Data for Actionable Edits - should be in 1/16 sprint",
                "Expanse Reports for Meditech Expanse",
                "Power BI Rehab DC Dashboard Detail Missing Volumes.",
                "Missing data in MTURC Mismatch report WE 1/21",
                "Add New Edit Numbers to AE Dashboard",
                "Unable to Report Volumes by Discharge Date",
                "Break-Fix: HIM Statistics Dashboard Displaying Incorrect Data",
                "The Totals in the HIM Rehab Accounts Dashboard Are Not Correct",
                "Rename 'Pivot' View",
                "Memorial Health - Meadows go live on CPART 1/1/2023",
                "November Release Edits for AE Dashboard - needed by 12/14",
                "New Edit Numbers for AE Dashboard - Due 12/15",
                "Updates Needed To/For Accruals",
                "Refresh Timing of HIM Analysis Dashboard - Needed by end of Nov",
                "Break-Fix: AE Dashboard Showing NULL as Coder ID and Empty Descriptions",
                "Accounts Missing from HIM Rehab Accounts Dashboard",
                "Break-Fix: Missing Facilities in Rehab Dashboard",
                "Break-Fix: AE Dashboard with ONLY Cerner accounts populating",
                "CAC_Interim_DRG_Reports Updates",
                "Unbilled/Coding Review Request",
                "Break-Fix: Coder 3-4 ID showing as NULL in BI Report for AE",
                "Account Discharge volumes with deleted codes 10/1/2021 thru 8/30/2022",
                "Request to add Edit #1125 and 1126 to AE Dashboard and Turn On Other Existing Edits",
                "In House Patient Report",
                "CRT OP Report for second level review",
                "Snapshot of Current State",
                "CPART data extract for Richmond",
                "OP Encounters Missing CAR-T HCPCS Code",
                "CDRA: Fin Allocation Process for Cancer Text File",
                "HPF CAC Data File Transfer",
                "Break-Fix: The AE Dashboard does not contain any data",
                "Actionable Edits Dashboard Data Research - EditKey",
                "HIM Analysis Dashboard Modifications - Removing Historical Data for Divested Facilities in Dashboard",
                "Question Marks appearing in Actionable Edit Dashboard and Reports",
                "Request to add AE Numbers for July SP1 Release",
                "Enhancement to CDRA PBI Operation Dashboard to include new tab for Cancer Registry",
                "HIM Analysis Dashboard Modifications - Day Scale",
                "Please add New and Revised Edits for July GR to the AE Dashboard",
                "HSC Responded Status Query Report",
                "HIM Analysis Dashboard Research & Modifications $$$",
                "Rehab Accounts Report - Enterprise",
                "Modification to CAC Documentation Analytics Report",
                "HIM Analysis Dashboard - HSC Alignment & Divested Facility Corrections",
                "Add edits to AE Dashboard",
                "Data Mart Report: CAC Documentation Analytics Report",
                "Data Sources for CCRM CAC Dashboard",
                "Modify VRM Automated Reports - Old SharePoint Automation",
                "Research Request: OP Edits Tracked in an OP Edit Dashboard",
                "Modify - Queries Saved and Not Sent Report",
                "Critical request to change VRM Responded query/CDI responded query reports into one report and add column for last coder",
                "CQR Team Outpatient CPT Backup Review 2022 (Quarterly)",
                "CQR Team Inpatient DRG Backup Review 2022 (Quarterly)",
                "Research Request for Market Realignment must be completed prior to 5/31/22",
                "Rapid Response Review Denominator IP Data Pull",
                "Rapid Response Outpatient CPT Denominator",
                "Request to Add Edits to Current AE Dashboard",
                "Automating CDRA Finance/Operations Dashboards",
                "CDRA Finance Dashboard: Update to Conversion Tables",
                "Queries launched on OB patients at HDH related to maternal or gestational HTN.",
                "Modify AE Dashboard",
                "Transition RAAA Reporting to HIM BI Tools",
                "Need VRM Vendor Automated Reports Destination Location Updated",
                "HIM Enterprise Analysis PBI Dashboard",
                "Modify AE Dashboard- Cerner Data coming in Blank",
                "VRM Actionable Edit- Hard Hold Reason",
                "Modify AE Dashboard- CoderVendor Column",
                "Update CPART Volume Monitoring Report In/Out CPART Volume",
                "MDC 5 Circulatory System",
                "OB Focus (SMM/NTSV)",
                "Update Actionable Edit Report- Configuration File",
                "Pull Preliminary Query Data for VRM for past 90 days",
                "OB Mortality Review",
                "NTSV C-Section",
                "Need to add CDI queries to current pull for query response report for vendors",
                "OCNQ/UCNQ Analysis",
                "NTSV C-Section Total Company Volume",
                "Replace CCRM in any file name, folder name, pathway and database with VRM",
                "Report of Scanned OB H&Ps",
                "Richmond Reoccurring Sepsis Query Report",
                "Update COID's for Coder_Info Table Pull",
                "December Sepsis Query Report",
                "Update to Enterprise CDI Report",
                "Richmond Sepsis Query Report",
                "Vendor Query Responses Report update needed",
                "Request for CustomCDI001 HCA Physician Query Detail Listing to be pulled on 12/1",
                "Using this report to identify volume, change rate based on changing the cardiac cath procedure code, and reimbursement impact of the change.",
                "AS DRG to PA eTran upload,",
                "CDI001 Report request",
                "Medical Necessity write off potentially impact by Mock Abstract Processes (Report)",
                "Automated Query Impact Monthly Report",
                "Code Level Accuracy Data",
                "Identify which accounts from results of HA-676 were reviewed in CPART",
                "DRG Impact from Cath Report Documentation",
                "Enterprise CDI Query Report",
                "CCRM requesting a report containing all queries that are in 'responded' status in CAC",
                "COVID Volume with POA of N",
                "Request for CustomCDI001 HCA Physician Query Detail Listing to be pulled on 10/1",
                "Need Base Numbers for 2022 Volume Projections",
                "Cardiac DRG Volumes"


            };

            string[] OldJob =
            { 
                "11PM CAC SLR Holds",
                "AS_DRG_LATEDOCUMENTATION",
                "AS_Query-Withdraw",
                "Automated Query Impact Monthly Report",
                "CAC Final Coded Pending Queries",
                "CAC OPS and QUERY Extract",
                "CAC OPS Extract PrePROD",
                "CAC_APT_Review_expanse",
                "CAC_AS_DRG_Analytics",
                "CAC_AS_DRG_Analytics_Monthly",
                "CAC_AS_DRG_Data_Pul",
                "CAC_CAPD_Query_Admit_Hold_TAT",
                "CAC_CCRM_Auditor_Review",
                "CAC_Coded_Volume",
                "CAC_Coding_Status",
                "CAC_Deleted_Queries",
                "CAC_DEMO",
                "CAC_Documentation_Analytics",
                "CAC_ED_Admits_Report_Monthly",
                "CAC_ED_Single_Path_Review",
                "CAC_EM_II_Pull",
                "CAC_Followup_Worklist",
                "CAC_FollowUp_WorkList_Monthly",
                "CAC_Inactive_Accounts",
                "CAC_IP_Prebill_Edit_Outcomes",
                "CAC_KEY_VOLUME_EM_II_eRequest",
                "CAC_Missing_Text_Report",
                "CAC_Productivity_Report",
                "CAC_Prod_Report_excel_version",
                "CAC_Query_After_Final_Coded",
                "CAC_Query_Automated_Impact_Report",
                "CAC_QUERY_DASHBOARD",
                "CAC_Query_For_Divisions",
                "CAC_Query_PCT_Final_Bill",
                "CAC_Query_Saved_Not_Sent",
                "CAC_WORKLIST_COMPARE",
                "CAC_Worklist_Dashboard",
                "CAC_Worklist_Params",
                "CAT-ETL",
                "CAT-ETL 7PM",
                "CAT_DB_Cleanup",
                "CAT_Unspecified_Laterality_Queries",
                "CCRM Checkedout",
                "CCRM_CMN",
                "CCRM_CPT_Monthly_Export",
                "CCRM_CQR_LOG",
                "CCRM_NMI_CAC",
                "CDI_CAC_Code_Volume_Report",
                "CDI_Worksheet_Dashboard",
                "CIS Meditech Comparisoni",
                "Coder_Info_Update",
                "CompAcctMgmt7+",
                "CompMgmt7+",
                "CPART EDW Pshell Alerting",
                "CPART-RETRO-EDW",
                "CPART-Richmond-Output",
                "CPART_CAC_EDW_COMPARE",
                "CPART_CAC_STATUS",
                "CPART_Completed_Accounts",
                "CPART_Evening_Analytics_Report",
                "CPART_HSC_Accuracy",
                "CPART_Morning_Analytics_Report",
                "CPART_QIO_Tracking_Process",
                "CPART_SPINAL_FUSION",
                "CPART_Vendor_Monitor",
                "CQR_EM_II_CAC_expense",
                "CQR_EM_II_Monthly",
                "CQR_IP_Rehab",
                "CRT_OP_Coverage Audit Report",
                "D519_report_for_VRM",
                "Daily_HPF_Discharge_Volume",
                "Deficiency_Assignment_and_Missing_OP",
                "Discharged_RCR_Wound_Care_Accounts",
                "Discharge_Volume_EDW",
                "Disk Cleanup",
                "Disk Space Report for Server - Email",
                "EDWCV_Results_CAC_Hold Report",
                "EDW_Monthly_Diagnosis_Procedure_Codes",
                "EDW_Newborn_coding_mismatch",
                "EDW_Outpatient_CPT_Modifier",
                "EDW_PATIENT_DAILY",
                "EDW_Patient_Unbilled_ETL",
                "EDW_Proc_Manually_Run",
                "EDW_Provider_Unbilled_ETL",
                "EDW_Unspecified_VS_Specified",
                "EPIC_Query_Extract_File_Move",
                "eRequest_Accounts",
                "eRequest_BilledOpenQueries_Unbilled_ETL",
                "eRequest_BOQ_Patient_Accounts",
                "eRequest_D-519",
                "ETL_Scripts_Backup",
                "HAC_CPART_Compare_Report",
                "HAC_CPART_Report_Output",
                "HIS_Accounts",
                "HPF Demographic Pull hourly",
                "HPF Job Queue",
                "HPF_Discharge_Volume",
                "HPF_DM_QUEUE_DASHBOARD",
                "HPF_Missing_Text_action",
                "HPF_Monthly_Documentation",
                "HPF_Queue_Dashboard",
                "HPF_Queue_Specialty_Volume",
                "HPF_Queue_Volume",
                "ICC_Volume_Monthly",
                "ICC_VOLUME_MONTHLY_COPY_FILES",
                "ICC_Volume_Reports",
                "Infusion_Extract",
                "Launch QChain",
                "Linked Server List Sync",
                "MicrosoftEdgeUpdateTaskMachineCore{4F2C9",
                "MicrosoftEdgeUpdateTaskMachineUA{02CC0AF",
                "Mission_Daily_Volume",
                "Monthly_DJ03_eRequest_Volume",
                "Monthly_DM_Dashboard",
                "Move_Kronos_files_For_DI_DM_Report",
                "MPF Query Report",
                "MTX_Straddle_Accounts",
                "NMI_Rejections_Unbilled",
                "npcapwatchdog",
                "OOWF_New",
                "Operative Report",
                "OP_Encounters_Missing_CAR-T_HCPCS_Code",
                "OP_Wound_Care",
                "PART Status Backlog and Aging",
                "PBI_Coding_Sessions",
                "Preliminary_Query_Data",
                "Review_Status_Update",
                "SensorFramework-LogonTask-{bcdb2b8f-9c59",
                "Submission_of_UBT_notes_via_SN_lines",
                "teamroomcopy-powershell-test",
                "Temporary - One Time Run of Month end fi",
                "UBT_EDW_Revenue",
                "URC_Dashboard",
                "Vendor Q Dashboard",
                "VRM_Weekly_CPART_Abstract",
                "Weekly Query Response",
                "Weekly UAP EDW",
                "Weekly UAP New",
                "Weekly_UAP",
                "WFTQ - Monthly Files",
                "WFTQ ETL - Daily",
                "WFTQ ETL Sum - Daily",
                "ZZ_TEST_ONETIME"

            };

            for (int i = 0; i < ShaleenJob.Length; i++)
            {
                for (int o = 0; o < OldJob.Length; o++)
                {
                    if (ShaleenJob[i].ToLower().Contains(OldJob[o].ToLower()))
                    {
                        Console.WriteLine($"Yes {ShaleenJob[i]} is Shaleen's job");
                    }
                }

            }

            Console.ReadKey();
        }
    }
}
